# Generated by Django 4.1 on 2022-08-08 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotes',
            name='header',
        ),
        migrations.RemoveField(
            model_name='quotes',
            name='link',
        ),
    ]
