# Generated by Django 4.1 on 2022-08-08 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0002_remove_quotes_header_remove_quotes_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='link',
        ),
    ]
