# Generated by Django 4.1 on 2022-08-10 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0004_remove_author_quote_quotes_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotes',
            old_name='author',
            new_name='authors',
        ),
    ]
